#ifndef BEELINE_H_
#define BEELINE_H_

/**
 * include
 */
#include <vector>

#include "IEntity.h"
#include "IStrategy.h"
#include "math/vector3.h"
/**
 * @brief this class inherits from the IStrategy
 * class and is responsible for generating the Beeline route
 * that the drone will take.
 */
class BeelineStrategy : public IStrategy {
 public:
  /**
   * @brief Constructor.
   * @param position Vector3 object representing the starting position
   * @param destination Vector3 object representing the destination
   * @param graph Igraph* object representing the graph
   */
  BeelineStrategy(Vector3 position, Vector3 destination);

  /**
   * @brief Destructor
   */
  ~BeelineStrategy();

  /**
   * @brief Moves a given entity with a path generated by an astar strategy
   * @param entity IEntity* - entity to be moved
   * @param dt double delta time
   */
  void Move(IEntity* entity, double dt);

  /**
   * @brief Returns true if path is completed
   */
  bool IsCompleted();

 private:
  Vector3 position;
  Vector3 destination;
};      // end class
#endif  // BEELINE_H_
