#ifndef ISTRATEGY_H_
#define ISTRATEGY_H_

#include <vector>

#include "IEntity.h"
#include "graph.h"

using namespace routing;

/**
 * @brief Interface for strategies in strategy pattern in simulation.
 */

class IStrategy {
 public:
  /**
   * @brief Moves a given entity with a path generated by an astar strategy
   * @param entity IEntity* - entity to be moved
   * @param dt double delta time
   */
  virtual void Move(IEntity* entity, double dt) = 0;

  /**
   * @brief Returns true if path is completed
   */
  virtual bool IsCompleted() = 0;

 protected:
  // IGraph object to be used in the simulation.
  const IGraph* graph;
};  // close class

#endif  // ISTRATEGY_H_
